### ISSUE TITLE
Option Helper

### ISSUE THREAD

**Issue by Diddyy** [OwenMelbz/nova-radio-field#1]
Hello!

Great package, I have just started using it myself although I have thought of a way to improve the package!

It would be great to be able to add a helper field under the radio buttons. I have added a screenshot to show you what I mean.
![Example](https://i.imgur.com/H10dlAa.png)

How I image this could be achieved is like this;
```
RadioButton::make('Administrator type', 'is_super_admin')
    ->options([
         0 => 'Regular administrator',
         1 => ['Super administrator','Super administrators have all administrator permissions and can manage other admins.'],
    ])
```

It is just an idea! :)

**Comment by Diddyy** [comment]
I have made the change that works for me in #2  :)

**Comment by OwenMelbz** [comment]
Hi @Diddyy :) thanks for the contribution, I'll merge it, have a tinker and try release tonight 👌🏼

**Comment by OwenMelbz** [comment]
Hi @Diddyy I've just released 0.0.3 and updated the readme.

I've tweaked it a little to use some helper functions to keep backwards compatibility and changed the syntax a little to keep it consistent with the other key-pair functionality.

If you're interested heres the commit https://github.com/OwenMelbz/nova-radio-field/commit/8cec439f08ec2b1303fac1098225135016159b57

Thanks again for your input :) always appreciated!

**Comment by Diddyy** [comment]
Hi Owen, thanks for tweaking and adding!

As my first open source contribution - even though I’ve been on GitHub for years it was always going to be a little rough, just found your great package and had an idea on how to improve it slightly!

Thanks for taking my idea into consideration and adding it! Great package, hope to see some more from you! 😉

**Comment by Diddyy** [comment]
@OwenMelbz Proposed a new pull request, fixes detailfied.vue and indexfield.vue as your latest changes did not change those files! They are still using my old method! #3 

Thanks :)

**Comment by Diddyy** [comment]
#3

**Comment by OwenMelbz** [comment]
@Diddyy thanks for pointing this out :)

I've migrated the shared functionality into a mixin so we don't have to copy/paste it into a variety of places and released the ability to toggle the visibility of other fields in version 0.0.5.

Thanks for helping!
