### ISSUE TITLE
->required() and ->rules('required')  does not seem to work

### ISSUE THREAD

**Issue by vayurobins** [OwenMelbz/nova-radio-field#10]
Hi. Thanks for this package. I have tried to add ->rules('required') and ->required() but neither seem to have any effect.
I was able to make a custom check though like this:
```
RadioButton::make(__('Select a Subscription'), 'plan')
    ->rules('required', function($attribute, $value, $fail) {
        if ($value == 'undefined') {
            return $fail(__('Please select a plan, this is required!'));
        }
    })
```

**Comment by OwenMelbz** [comment]
Hi,

Have you looked at what the value that gets posted is when nothing is selected?

(I’ve not used nova in over a year so I can’t really quickly check this)

If your able to submit a PR, I can merge and release

**Comment by vayurobins** [comment]
Hi.
Yes this: $value == 'undefined'

**Comment by OwenMelbz** [comment]
Have you tried setting a default value?

**Comment by vayurobins** [comment]
No, but I don't think there should be one though. I want the user to think about the choice and select :-)

**Comment by OwenMelbz** [comment]
as in have you tried setting the default to something else e.g null

**Comment by vayurobins** [comment]
Ok, I have now tested setting 
```
->default(null)
->required()
```
That did not give any message feedback to the user, it just throws an error. So same error as before

**Comment by JoshMoreno** [comment]
I've submitted a PR #13 , but as a temporary workaround you can use the required validation rule, but you must pass an empty string as the default value.

```php
RadioButton::make()
    ->default('')
    ->rules('required')
    // ...
```
