### ISSUE TITLE
Radio button styling issue?

### ISSUE THREAD

**Issue by vdhruv** [OwenMelbz/nova-radio-field#11]
the radio button is displaying in base HTML style instead of nova theme. can anyone suggest me how to apply nova theme assets to this radio button.
![image](https://user-images.githubusercontent.com/35102375/73125253-cb00ea80-3fca-11ea-9428-9f4453cab340.png)

**Comment by JoshMoreno** [comment]
Do you mean how to style the radio button?
In your nova service provider boot method you can register additional css
```
Nova::style('radio-button', asset('css/radio-button.css'));
```

Or override the form field entirely by specifying what component to use in your nova resource
```
RadioButton::make('My Field')->component('my-custom-component')
```

Or globally override in your nova service provider boot method
```
RadioButton::useComponent('my-custom-component');
```

**Comment by apepindev** [comment]
I've added 'checkbox' class selector to the input to get it looking consistent.
