### ISSUE TITLE
Array is not updated

### ISSUE THREAD

**Issue by Jun-ocx** [OwenMelbz/nova-radio-field#18]
First of all, this package is awesome!
I appreciate but I encounter an issue

```php            
RadioButton::make('Enable Service','services')
                ->options(
                    [
                        3 => ['Client' => 'FAAS'],
                        5 => ['Marketplace' => 'Shopify']
                    ]
                )
                ->stack()
                ->default(3)
                ->required()
                ->sortable()
                ->hideFromIndex(),
```

These value stored as an array in DB ex) [3] OR [5] under services column
but in update page, the selected option is gone. Screenshot is attached

![Screen Shot 2020-09-17 at 10 28 33 AM](https://user-images.githubusercontent.com/55770199/93506051-8bc43880-f8d0-11ea-9a9f-8e2889ed24f6.png)

**Comment by OwenMelbz** [comment]
Hi @Jun-ocx

Just to confirm, these are saving correctly, but just not displaying correctly on the edit screen?

Could you try replacing the key names with strings as a test please?

e.g.

```php
'3' => ['Client', 'FAAS]
```
