### ISSUE TITLE
Can we put img or rendered data instead of string?

### ISSUE THREAD

**Issue by aozen** [OwenMelbz/nova-radio-field#4]
I know there is no such thing yet. But if you can it will be great.

```
->options([

         0 => '<p class="greatjob">string values with some styles</p>',

         1 => '<img src="somepath">',

   ])
```

**Comment by OwenMelbz** [comment]
Hi, I’m away at the moment so can’t really look myself - are you able to provide a screenshot of what happens currently if you do that?

Additionally are you in a position to submit a PR for the feature to get it moving faster?

**Comment by aozen** [comment]
I didn't do anything yet. I don't have any time for do something and pr in a couple of days.

I just requested. If you can, make clickable images or put image to next of the radio button. 
For example: 
Question: Which OS are you using?
Radios: 1) windows 2) linux

Instead of displaying string windows and linux. We can put windows logo and linux logo. 
I am just saying that. Sorry about my english :)

I can do that after 15days i think. But if you can right now i will use this immediately :)

**Comment by OwenMelbz** [comment]
Have you been able to look into this any more?
