### ISSUE TITLE
Why add flex to wrapper ?

### ISSUE THREAD

**Issue by donkfather** [OwenMelbz/nova-radio-field#9]
Hi,

Why have these 2 lines? 
```
                container.classList.add('flex');
                container.classList.add('items-center');
```
IMO it looks better if the error and radio buttons are stacked.

**Comment by donkfather** [comment]
in addition having flex on the wrapper makes the 'Hint' glued to the last option

**Comment by OwenMelbz** [comment]
Can you provide any screenshots as to what you mean please?
